[package]
name = "wasm-interp"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "0.19.1", default-features = false, features = ["std"] }
serde = { version = "1.0", default-features = false }
wasmi = "0.29"
